name: Deploy Abhyaz React app to Elastic Beanstalk
on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t abhyaz-app .
          docker tag abhyaz-app:latest murugeshks/abhyaz-app:latest
          docker push murugeshks/abhyaz-app:latest

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: abhyaz-app
          environment_name: Abhyaz-app-env-1
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-ap-south-1-356303048610
          region: ap-south-1
          deployment_package: deploy.zip