name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t my-react-app .
          docker tag my-react-app:latest YOUR_DOCKERHUB_USERNAME/my-react-app:latest
          docker push YOUR_DOCKERHUB_USERNAME/my-react-app:latest

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name Your-Application-Name \
            --version-label v1 --source-bundle S3Bucket="elasticbeanstalk-your-region-ID",S3Key="docker/my-react-app.zip"
          aws elasticbeanstalk update-environment --application-name Your-Application-Name \
            --environment-name Your-Environment-Name --version-label v1
